language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database voyager_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan voyager:install
  - php artisan key:generate

script:
  - vendor/bin/phpunit